apiVersion: v1
kind: Secret
metadata:
  name: {{ include "appname.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "appname.fullname" . }}
    app.kubernetes.io/managed-by: "helm"
    helm.sh/chart: {{ include "appname.name" . }}-{{ include "appname.release" . }}
data:
  DB_PASSWORD: {{ default .Values.secrets.DB_PASSWORD .Values.DB_PASSWORD | b64enc }}
  MQ_PASSWORD: {{ default .Values.secrets.MQ_PASSWORD .Values.MQ_PASSWORD | b64enc }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  namespace: databases
  name: {{ include "appname.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "appname.fullname" . }}
    app.kubernetes.io/managed-by: "helm"
    helm.sh/chart: {{ include "appname.name" . }}-{{ include "appname.release" . }}
data:
  DB_PASSWORD: {{ default .Values.secrets.DB_PASSWORD .Values.DB_PASSWORD | b64enc }}
type: Opaque
